#!/bin/bash
# 01-network.sh - configure persistent MAC and hostname
#
# Problem solved: AM62 SK board has no MAC EEPROM, so kernel generates random MAC
# on every boot. This breaks DHCP reservations. Solution: systemd-networkd .link
# unit pinning MAC to specific HW path.

set -e

LINK_FILE="/etc/systemd/network/00-eth1-mac.link"

echo "[*] Setting persistent MAC: $BRAMKA_MAC on $ETH_INTERFACE_NAME (HW: $ETH_HW_PATH)"

# Create systemd network link file (idempotent - overwrites if exists):
cat > "$LINK_FILE" << EOF
# Auto-generated by bramka-setup
# Persistent MAC for AM62 SK ethernet (no EEPROM, kernel would randomize otherwise)

[Match]
Path=$ETH_HW_PATH
OriginalName=eth*

[Link]
MACAddressPolicy=none
MACAddress=$BRAMKA_MAC
NamePolicy=
Name=$ETH_INTERFACE_NAME
EOF

echo "[*] Created $LINK_FILE"

# Set hostname (persistent + runtime):
echo "[*] Setting hostname: $BRAMKA_HOSTNAME"
if command -v hostnamectl &> /dev/null; then
    hostnamectl set-hostname "$BRAMKA_HOSTNAME"
else
    echo "$BRAMKA_HOSTNAME" > /etc/hostname
    hostname "$BRAMKA_HOSTNAME"
fi

# Update /etc/hosts for local resolution:
if ! grep -q "127.0.1.1.*$BRAMKA_HOSTNAME" /etc/hosts; then
    # Remove any existing 127.0.1.1 line:
    sed -i '/^127\.0\.1\.1/d' /etc/hosts
    # Add new one:
    echo "127.0.1.1  $BRAMKA_HOSTNAME" >> /etc/hosts
    echo "[*] Updated /etc/hosts with $BRAMKA_HOSTNAME"
fi

echo "[*] Network module complete"
echo "    MAC takes effect after reboot"
echo "    Configure DHCP reservation in router: MAC=$BRAMKA_MAC"
