#!/bin/bash
# 04-go.sh - install Go toolchain
#
# Problem solved: Arago default image doesn't include Go compiler.
# Without it, Deploy-Go -Build from laptop fails with "go: command not found".
# Also Arago doesn't create /usr/local by default - we need to mkdir it.
#
# Solution: download official Go binary for aarch64, install to /usr/local/go,
# create symlinks to /usr/bin/ for non-interactive shells (Deploy-Go, systemd),
# and set global PATH via /etc/profile.d/.
#
# Idempotent: detects existing install and skips if version matches.
set -e

# === CONFIG ===
GO_VERSION="${GO_VERSION:-1.23.4}"
GO_INSTALL_DIR="/usr/local/go"
GO_TARBALL="go${GO_VERSION}.linux-arm64.tar.gz"
GO_URL="https://go.dev/dl/${GO_TARBALL}"

# === DETECT EXISTING INSTALL ===
if [ -x "${GO_INSTALL_DIR}/bin/go" ]; then
    CURRENT_VERSION=$("${GO_INSTALL_DIR}/bin/go" version | awk '{print $3}' | sed 's/^go//')
    if [ "$CURRENT_VERSION" = "$GO_VERSION" ]; then
        echo "[*] Go ${GO_VERSION} already installed at ${GO_INSTALL_DIR}, skipping download"
        SKIP_DOWNLOAD=1
    else
        echo "[*] Go ${CURRENT_VERSION} found, upgrading to ${GO_VERSION}"
    fi
fi

# === ARCHITECTURE CHECK ===
ARCH=$(uname -m)
if [ "$ARCH" != "aarch64" ]; then
    echo "ERROR: This script supports aarch64 only, got: $ARCH"
    echo "       Edit GO_TARBALL in this script for other architectures."
    exit 1
fi

# === DOWNLOAD + INSTALL ===
if [ -z "${SKIP_DOWNLOAD:-}" ]; then
    echo "[*] Downloading Go ${GO_VERSION} for aarch64..."

    cd /tmp
    if [ ! -f "$GO_TARBALL" ]; then
        wget -q --show-progress "$GO_URL" || {
            echo "ERROR: Failed to download $GO_URL"
            echo "       Check internet connection or download manually."
            exit 1
        }
    fi

    echo "[*] Extracting to ${GO_INSTALL_DIR}..."
    # Arago doesn't create /usr/local by default - mkdir it:
    mkdir -p /usr/local
    rm -rf "${GO_INSTALL_DIR}"
    tar -C /usr/local -xzf "$GO_TARBALL"
    rm -f "/tmp/${GO_TARBALL}"

    echo "[*] Go ${GO_VERSION} extracted"
fi

# === GLOBAL PATH for interactive shells ===
PROFILE_FILE="/etc/profile.d/go.sh"
cat > "$PROFILE_FILE" << 'EOF'
# Auto-generated by bramka-setup (04-go.sh)
export PATH=$PATH:/usr/local/go/bin
export GOPATH=/root/go
EOF
chmod +x "$PROFILE_FILE"
echo "[*] Created ${PROFILE_FILE} (loads PATH for interactive shells)"

# === SYMLINKS for non-interactive shells ===
# Deploy-Go uses non-interactive SSH which may not source /etc/profile.d/.
# Symlinks to /usr/bin/ ensure `go` works even without PATH setup.
if [ ! -L /usr/bin/go ] || [ "$(readlink /usr/bin/go)" != "${GO_INSTALL_DIR}/bin/go" ]; then
    ln -sf "${GO_INSTALL_DIR}/bin/go" /usr/bin/go
    echo "[*] Symlinked /usr/bin/go -> ${GO_INSTALL_DIR}/bin/go"
fi
if [ ! -L /usr/bin/gofmt ] || [ "$(readlink /usr/bin/gofmt)" != "${GO_INSTALL_DIR}/bin/gofmt" ]; then
    ln -sf "${GO_INSTALL_DIR}/bin/gofmt" /usr/bin/gofmt
    echo "[*] Symlinked /usr/bin/gofmt -> ${GO_INSTALL_DIR}/bin/gofmt"
fi

# === GOPATH DIRECTORY ===
mkdir -p /root/go/{src,pkg,bin}
echo "[*] Created GOPATH structure in /root/go/"

# === VERIFY ===
INSTALLED_VERSION=$(/usr/local/go/bin/go version)
echo "[*] Verification: $INSTALLED_VERSION"

echo "[*] Go module complete"
echo "    For interactive shell: 'source /etc/profile.d/go.sh' or relogin"
echo "    Non-interactive (systemd, ssh commands): /usr/bin/go works directly"
