/** \mainpage Driver Overview
  *
  * \section section_drv_info Driver Information
  * This Sensor Controller Interface driver has been generated by the Texas Instruments Sensor Controller
  * Studio tool:
  * - <b>Project name</b>:     Capacitive Touch for ULPSENSE
  * - <b>Project file</b>:     C:/SmartHome/Nodes/LightSwitchNode/Firmware/SensorController/CapacitiveTouch.scp
  * - <b>Code prefix</b>:      -
  * - <b>Operating system</b>: TI-RTOS
  * - <b>Tool version</b>:     2.9.0.208
  * - <b>Tool patches</b>:     None
  * - <b>Target chip</b>:      CC1312R1F3, package QFN48 7x7 RGZ, revision E (2.1) or F (3.0)
  * - <b>Created</b>:          2026-08-21 01:49:11.021
  * - <b>Computer</b>:         DESKTOP-S5PV63S
  * - <b>User</b>:             damia
  *
  * No user-provided resource definitions were used to generate this driver.
  *
  * No user-provided procedure definitions were used to generate this driver.
  *
  * Do not edit the generated source code files other than temporarily for debug purposes. Any
  * modifications will be overwritten by the Sensor Controller Studio when generating new output.
  *
  * \section section_drv_modules Driver Modules
  * The driver is divided into three modules:
  * - \ref module_scif_generic_interface, providing the API for:
  *     - Initializing and uninitializing the driver
  *     - Task control (for starting, stopping and executing Sensor Controller tasks)
  *     - Task data exchange (for producing input data to and consume output data from Sensor Controller
  *       tasks)
  * - \ref module_scif_driver_setup, containing:
  *     - The AUX RAM image (Sensor Controller code and data)
  *     - I/O mapping information
  *     - Task data structure information
  *     - Driver setup data, to be used in the driver initialization
  *     - Project-specific functionality
  * - \ref module_scif_osal, for flexible OS support:
  *     - Interfaces with the selected operating system
  *
  * It is possible to use output from multiple Sensor Controller Studio projects in one application. Only
  * one driver setup may be active at a time, but it is possible to switch between these setups. When
  * using this option, there is one instance of the \ref module_scif_generic_interface and
  * \ref module_scif_osal modules, and multiple instances of the \ref module_scif_driver_setup module.
  * This requires that:
  * - The outputs must be generated using the same version of Sensor Controller Studio
  * - The outputs must use the same operating system
  * - The outputs must use different source code prefixes (inserted into all globals of the
  *   \ref module_scif_driver_setup)
  *
  *
  * \section section_project_info Project Description
  * Demonstrates capacitive touch on LaunchPad with the ULP Sense BoosterPack (BOOSTXL-ULPSENSE), with
  * processing.
  * 
  * The Sensor Controller samples the two capacitive touch areas on the ULP Sense BoosterPack, using the
  * COMPA, ISRC and TDC peripherals.
  * The Sensor Controller processes the resulting TDC values in order to detect touch. Note that this
  * touch detection algorithm is only an example of the Sensor Controller's processing capabilities, and
  * should not be used in production.
  * 
  * The default sampling frequency is 32 Hz while touch is not detected, and ~100 Hz while touch is
  * detected.
  * 
  * Touch detection is communicated to the System CPU application, which enables LEDs on the LaunchPad
  * while touch is detected.
  * 
  * Task Testing should only be used for debugging purposes, as it will not run the Capacitive Touch task
  * at the correct rate. Use Run-Time Logging for testing, performance evaluation and tuning.
  * 
  * BOOSTXL-ULPSENSE SETUP:
  * - Make sure that the supplied plexiglass is securely mounted over the capacitive touch buttons,
  * without any air gaps.
  * - Remove all jumpers
  * 
  * See the header in the application source file ("main_tirtos.c") for further details and instructions.
  * This file is located in the source code output directory.
  *
  *
  * \subsection section_io_mapping I/O Mapping
  * Task I/O functions are mapped to the following pins:
  * - Capacitive Touch:
  *     - <b>AXD: Capacitive touch area 0</b>: DIO27
  *     - <b>AXD: Capacitive touch area 1</b>: DIO29
  *     - <b>AXS: Cap touch external reference resistor</b>: DIO24
  *
  *
  * \section section_task_info Task Description(s)
  * This driver supports the following task(s):
  *
  *
  * \subsection section_task_desc_capacitive_touch Capacitive Touch
  * Samples the capacitive touch buttons on the ULP Sense BoosterPack., using the COMPA, ISRC and TDC
  * peripherals, and performs touch detection.
  * 
  * The following is performed for each touch area:
  * - The ISRC peripheral is used to charge the touch area to 0.6 V, which generates a rising edge on the
  * COMPA output. The COMPA reference is then changed to 2.4 V (with a temporary boost to 3.3 V), and
  * charging continues until a second rising edge occurs on the COMPA output.
  * - The TDC is used to measure the time between these two COMPA output rising edges. The TDC value is
  * used by the touch detection algorithm.
  * - To filter out noise, such as 50/60 Hz, the touch detection algorithm works on the average value of
  * the N last TDC values.
  * - While touch is not detected, a baseline value is updated slowly. While touch is detected, a high
  * value is updated.
  * - The touch detection threshold is in the middle between the high value and the baseline value.
  * 
  * The sample rate is increased while touch is detected on one or more touch areas.
  * 
  * The System CPU application is notified for each task iteration during touch detection, and one time
  * when touch detection ends.
  * 
  * Task Testing should only be used for debugging purposes, as it will not run the Capacitive Touch task
  * at the correct rate. Use Run-Time Logging for testing, performance evaluation and tuning.
  * 
  * BOOSTXL-ULPSENSE SETUP:
  * - Make sure that the supplied plexiglass is securely mounted over the capacitive touch buttons,
  * without any air gaps.
  * - Remove all jumpers
  *
  */




/** \addtogroup module_scif_driver_setup Driver Setup
  *
  * \section section_driver_setup_overview Overview
  *
  * This driver setup instance has been generated for:
  * - <b>Project name</b>:     Capacitive Touch for ULPSENSE
  * - <b>Code prefix</b>:      -
  *
  * The driver setup module contains the generated output from the Sensor Controller Studio project:
  * - Location of task control and scheduling data structures in AUX RAM
  * - The AUX RAM image, and the size the image
  * - Task data structure information (location, size and buffer count)
  * - I/O pin mapping translation table
  * - Task resource initialization and uninitialization functions
  * - Hooks for run-time logging
  *
  * @{
  */
#ifndef SCIF_H
#define SCIF_H

#include <stdint.h>
#include <stdbool.h>
#include "scif_framework.h"
#include "scif_osal_tirtos.h"


/// Target chip name
#define SCIF_TARGET_CHIP_NAME_CC1312R1F3
/// Target chip package
#define SCIF_TARGET_CHIP_PACKAGE_QFN48_7X7_RGZ

/// Number of tasks implemented by this driver
#define SCIF_TASK_COUNT 1

/// Capacitive Touch: Task ID
#define SCIF_CAPACITIVE_TOUCH_TASK_ID 0


/// Capacitive Touch: Baseline update period when not touching
#define SCIF_CAPACITIVE_TOUCH_BASELINE_UPDATE_PERIOD 32
/// Capacitive Touch: Default ISRC current = 1 uA (BV_ISRC_CURR_1P0U)
#define SCIF_CAPACITIVE_TOUCH_D_ISRC_CURRENT 17
/// Capacitive Touch: Default maximum sample period
#define SCIF_CAPACITIVE_TOUCH_D_MAX_SMPL_PERIOD 128
/// Capacitive Touch: Default minimum sample period
#define SCIF_CAPACITIVE_TOUCH_D_MIN_SMPL_PERIOD 40
/// Capacitive Touch: Division exponent for IIR filter of mean value of the low-mean window
#define SCIF_CAPACITIVE_TOUCH_LOW_MEAN_IIR_DIV_EXP 2
/// Capacitive Touch: Update period of IIR filter of mean value of the low-mean window
#define SCIF_CAPACITIVE_TOUCH_LOW_MEAN_IIR_UPDATE_PERIOD 64
/// Capacitive Touch: Exponent that determines LOW_MEAN_WINDOW_SIZE
#define SCIF_CAPACITIVE_TOUCH_LOW_MEAN_WINDOW_EXP 3
/// Capacitive Touch: Number of low mean values stored for each pin
#define SCIF_CAPACITIVE_TOUCH_LOW_MEAN_WINDOW_SIZE 8
/// Capacitive Touch: Total size of the low mean window array variable
#define SCIF_CAPACITIVE_TOUCH_LOW_MEAN_WINDOW_TOTAL 16
/// Capacitive Touch: Maximum number of TDC timeouts before a pin is regarded as stuck
#define SCIF_CAPACITIVE_TOUCH_MAX_TDC_TIMEOUTS 5
/// Capacitive Touch: 
#define SCIF_CAPACITIVE_TOUCH_MAX_TOUCH_ITERATIONS 1500
/// Capacitive Touch: Capactive touch pin count
#define SCIF_CAPACITIVE_TOUCH_PIN_COUNT 2
/// Capacitive Touch: Exponent that determines TDC_SMPL_WINDOW_SIZE
#define SCIF_CAPACITIVE_TOUCH_TDC_SMPL_WINDOW_EXP 3
/// Capacitive Touch: Number of last TDC values stored per pin
#define SCIF_CAPACITIVE_TOUCH_TDC_SMPL_WINDOW_SIZE 8
/// Capacitive Touch: Total size of the TDC sample window array variable
#define SCIF_CAPACITIVE_TOUCH_TDC_SMPL_WINDOW_TOTAL 16
/// Capacitive Touch: 
#define SCIF_CAPACITIVE_TOUCH_TOUCH_DETECT_OFFSET 12
/// Capacitive Touch: 
#define SCIF_CAPACITIVE_TOUCH_TOUCH_RELEASE_OFFSET 6
/// Capacitive Touch I/O mapping: Capacitive touch area
#define SCIF_CAPACITIVE_TOUCH_DIO_AXD_CAP_TOUCH { 27, 29 }
/// Capacitive Touch I/O mapping: Cap touch external reference resistor
#define SCIF_CAPACITIVE_TOUCH_DIO_AXS_CAP_TOUCH_REF 24


// All shared data structures in AUX RAM need to be packed
#pragma pack(push, 2)


/// Capacitive Touch: Task configuration structure
typedef struct {
    uint16_t isrcCurrent;          ///< ISRC current used to charge the touch areas (logical OR of BV_ISRC_CURR_XYZ constants)
    uint16_t maxSmplPeriod;        ///< Maximum sample period [0.25 ms]
    uint16_t minSmplPeriod;        ///< Minimum sample period [0.25 ms]
    uint16_t pAuxioAxdCapTouch[2]; ///< I/O mapping: Capacitive touch area
} SCIF_CAPACITIVE_TOUCH_CFG_T;


/// Capacitive Touch: Task output data structure
typedef struct {
    uint16_t bvTdcTimeout;          ///< Indicates TDC timeout error, one bit for each pin
    uint16_t bvTdcValueOverflow;    ///< Indicates TDC value overflow error, one bit for each pin
    int16_t  pBaselineValue[2];     ///< For observation, for each pin: Baseline value
    int16_t  pHighValue[2];         ///< For observation, for each pin: High value
    uint16_t pTdcSmplWindowMean[2]; ///< For observation, for each pin: Mean value of the TDC sample window
    uint16_t pTdcValueRaw[2];       ///< For observation, for each pin: Unfiltered TDC value
    int16_t  pThresValue[2];        ///< For observation, for each pin: Touch threshold value
    uint16_t pTouchDet[2];          ///< For each pin: Touch detected
} SCIF_CAPACITIVE_TOUCH_OUTPUT_T;


/// Capacitive Touch: Task state structure
typedef struct {
    uint16_t bvTdcTimeout;         ///< Indicates TDC timeout error, one bit for each pin
    uint16_t bvTdcValueOverflow;   ///< Indicates TDC value overflow error, one bit for each pin
    uint16_t genOutput;            ///< Generate output after the current iteration?
    uint16_t pBaselineValue[2];    ///< For each pin: Baseline value (expected TDC value when not touching)
    uint16_t pHighValue[2];        ///< For each pin: High value (expected TDC value when not touching)
    int16_t  pLowMeanIirFilter[2]; ///< For each pin: IIR-filtered mean value of the low mean window (used to update the baseline)
    uint16_t pLowMeanWindow[16];   ///< For each pin: Window of mean values of qualified TDC values while not touching
    uint16_t pTdcSmplLowCount[2];  ///< For each pin: Number of low TDC samples in row, used to control baseline update
    uint16_t pTdcSmplWindow[16];   ///< For each pin: Window of the last qualified TDC values
    uint16_t pTdcTimeoutCount[2];  ///< For each pin: Number of consecutive TDC timeouts
    uint16_t pTouchDet[2];         ///< For each pin: Touch currently detected
    uint16_t pTouchHoldCount[2];   ///< 
    uint16_t smplPeriod;           ///< Sample period [0.25 ms]
    uint16_t startupIterCount;     ///< Counts the number of task iterations performed during startup
} SCIF_CAPACITIVE_TOUCH_STATE_T;


/// Sensor Controller task data (configuration, input buffer(s), output buffer(s) and internal state)
typedef struct {
    struct {
        SCIF_CAPACITIVE_TOUCH_CFG_T cfg;
        uint16_t outputSceBufferCtrl;
        uint16_t outputDrvBufferCtrl;
        uint16_t outputScePtr;
        SCIF_CAPACITIVE_TOUCH_OUTPUT_T pOutput[3];
        SCIF_CAPACITIVE_TOUCH_STATE_T state;
    } capacitiveTouch;
} SCIF_TASK_DATA_T;

/// Sensor Controller task generic control (located in AUX RAM)
#define scifTaskData    (*((volatile SCIF_TASK_DATA_T*) 0x400E0170))


// Initialized internal driver data, to be used in the call to \ref scifInit()
extern const SCIF_DATA_T scifDriverSetup;


// Restore previous struct packing setting
#pragma pack(pop)


// AUX I/O re-initialization functions
void scifReinitTaskIo(uint32_t bvTaskIds);


// No task-specific API available


#endif
//@}


// Generated by DESKTOP-S5PV63S at 2026-08-21 01:49:11.021
